[[experiments]]
id = "test_exp_00"
n_progressions = 20
n_agents = 1

[[models]]
id = "optimizer_00"
label = "GD"
description = "Gradient Descent"
params_labels = ["learning_rate", "epsilon"]
params_values = [0.1, 0.001]

