[[experiments]]
id = "test_exp_00"
n_progressions = 20
n_agents = 1

# ------------------------------------------------------ Synthetic Market Generator -- //
# ------------------------------------------------------ -------------------------- -- //

[[exchanges]]
id = "test_ex_00"
region = "test_region_00"
name = "test_name_00"
category = "test_category_00"

[exchanges.orderbook]
update_freq = 20
bid_price = 3_000.00
bid_levels = [4, 12]
bid_orders = [5, 15]
ticksize = [0.2, 2.0]
ask_price = 3_001.00
ask_levels = [3, 13]
ask_orders = [6, 16]

[[models]]
id = "mod_00"
label = "GBM"
description = "Geometric Brownian Motion"
params_labels = ["mu", "sigma"]
params_values = [1e-3, 1e-6]
seed = 20995
